### ISSUE TITLE
run-time error

### ISSUE THREAD

**Issue by chaodongyang** [riklaunim/pyusb-keyboard-alike#8]
Traceback (most recent call last):
  File "D:/pyusb-keyboard-alike-master/pyqt_example.py", line 65, in <module>
    myapp = StartQT4()
  File "D:/pyusb-keyboard-alike-master/pyqt_example.py", line 30, in __init__
    self.rfidreader.initialize()
  File "D:\pyusb-keyboard-alike-master\keyboard_alike\reader.py", line 37, in initialize
    self._device = usb.core.find(idVendor=self.vendor_id, idProduct=self.product_id)
  File "C:\Python27\lib\site-packages\usb\core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by riklaunim** [comment]
That's a pyusb exception. Likely missing some system header libraries during compilation.
